### PR TITLE
Added wrapper script for the binary

### PR DESCRIPTION
**Pull request by schrepfler**

### CODE REVIEW

**Comment by JulienPalard** [comment]
Why not `cat $file | is_utf8 -` ?

**Comment by schrepfler** [comment]
Perfectly valid, it's that beginners don't immediately get how pipes work so I thought it would be easier to have a helper script.

**Comment by JulienPalard** [comment]
Why not changing the parameters to allow a file by default instead of a string ? Should look more complient with unix philosophy, like grep, sed, etc... ?

**Comment by schrepfler** [comment]
Looks to me this is now redundant?

**Comment by JulienPalard** [comment]
Right. Do you think we should allow multiple files too ? And do you think we should use stdin even if "-" is not given ?

**Comment by schrepfler** [comment]
It might be nice with multiple files, on the second question I'm not sure, it's what I've seen typically with unix commands so I think it's a good idiom.

**Comment by JulienPalard** [comment]
Will do, thanks for your feedback.

**Comment by schrepfler** [comment]
No problem.

**Pull request closed without merging**
